version: '2'

services:
  mysql:
    image: percona:5.7
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=ttrss
      - MYSQL_USER=ttrss
      - MYSQL_PASSWORD=ttrss
  ttrss:
    image: strowi/ttrss
    build: ./
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - mysql
